SCREEN_HEIGHT = 720
SCREEN_WIDTH = 1280
TARGET_FPS = 60

DEFAULT_TEXTURE_SCALE = 2

SLIME_TEXTURE_SCALE = 2
BUTTON_TEXTURE_SCALE = 2

class Scale(int):
    DEFAULT = 1
    DOUBLED = 2
    TRIPLED = 3
    QUADRUPLED = 4
